import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { LeftSidebar, RightSidebar } from "@/components/Sidebar";
import { NavigationProgress } from "@/components/NavigationProgress";
import { cn } from "@/lib/utils";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <NavigationProgress />
        {token && <Navbar />}
        <div className={cn("flex justify-between", !token && "justify-center")}>
          {token && <LeftSidebar />}

          {children}

          {token && <RightSidebar />}
        </div>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
